FROM phpmyadmin:latest

ENV PMA_HOST=localhost
ENV PMA_PORT=3307
ENV PMA_ARBITRARY=1

# Optional: Set upload size for SQL imports (example: 100M)
ENV PHP_UPLOAD_MAX_FILESIZE=100M
ENV PHP_POST_MAX_SIZE=100M